/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkMonitorRouteImport } from './routes/network-monitor'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsAssetIdRouteImport } from './routes/assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMonitorRoute = NetworkMonitorRouteImport.update({
  id: '/network-monitor',
  path: '/network-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network-monitor' | '/assets/$assetId' | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network-monitor' | '/assets/$assetId' | '/assets'
  id: '__root__' | '/' | '/network-monitor' | '/assets/$assetId' | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkMonitorRoute: typeof NetworkMonitorRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-monitor': {
      id: '/network-monitor'
      path: '/network-monitor'
      fullPath: '/network-monitor'
      preLoaderRoute: typeof NetworkMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkMonitorRoute: NetworkMonitorRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
