/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as NetworkMonitorRouteImport } from './routes/network-monitor'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsAssetIdRouteImport } from './routes/assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMonitorRoute = NetworkMonitorRouteImport.update({
  id: '/network-monitor',
  path: '/network-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit-log': typeof AuditLogRoute
  '/baseline': typeof BaselineRoute
  '/investigations': typeof InvestigationsRoute
  '/mitre': typeof MitreRoute
  '/network-map': typeof NetworkMapRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/protocols': typeof ProtocolsRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/zones': typeof ZonesRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit-log': typeof AuditLogRoute
  '/baseline': typeof BaselineRoute
  '/investigations': typeof InvestigationsRoute
  '/mitre': typeof MitreRoute
  '/network-map': typeof NetworkMapRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/protocols': typeof ProtocolsRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/zones': typeof ZonesRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit-log': typeof AuditLogRoute
  '/baseline': typeof BaselineRoute
  '/investigations': typeof InvestigationsRoute
  '/mitre': typeof MitreRoute
  '/network-map': typeof NetworkMapRoute
  '/network-monitor': typeof NetworkMonitorRoute
  '/protocols': typeof ProtocolsRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/zones': typeof ZonesRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/audit-log'
    | '/baseline'
    | '/investigations'
    | '/mitre'
    | '/network-map'
    | '/network-monitor'
    | '/protocols'
    | '/reports'
    | '/risk'
    | '/sensors'
    | '/settings'
    | '/threat-intelligence'
    | '/vulnerabilities'
    | '/zones'
    | '/assets/$assetId'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/audit-log'
    | '/baseline'
    | '/investigations'
    | '/mitre'
    | '/network-map'
    | '/network-monitor'
    | '/protocols'
    | '/reports'
    | '/risk'
    | '/sensors'
    | '/settings'
    | '/threat-intelligence'
    | '/vulnerabilities'
    | '/zones'
    | '/assets/$assetId'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/audit-log'
    | '/baseline'
    | '/investigations'
    | '/mitre'
    | '/network-map'
    | '/network-monitor'
    | '/protocols'
    | '/reports'
    | '/risk'
    | '/sensors'
    | '/settings'
    | '/threat-intelligence'
    | '/vulnerabilities'
    | '/zones'
    | '/assets/$assetId'
    | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuditLogRoute: typeof AuditLogRoute
  BaselineRoute: typeof BaselineRoute
  InvestigationsRoute: typeof InvestigationsRoute
  MitreRoute: typeof MitreRoute
  NetworkMapRoute: typeof NetworkMapRoute
  NetworkMonitorRoute: typeof NetworkMonitorRoute
  ProtocolsRoute: typeof ProtocolsRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
  ZonesRoute: typeof ZonesRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-monitor': {
      id: '/network-monitor'
      path: '/network-monitor'
      fullPath: '/network-monitor'
      preLoaderRoute: typeof NetworkMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuditLogRoute: AuditLogRoute,
  BaselineRoute: BaselineRoute,
  InvestigationsRoute: InvestigationsRoute,
  MitreRoute: MitreRoute,
  NetworkMapRoute: NetworkMapRoute,
  NetworkMonitorRoute: NetworkMonitorRoute,
  ProtocolsRoute: ProtocolsRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
  ZonesRoute: ZonesRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
